export default class Service {
    _product = [
        {id: 1, name: "ttttttttttttt ",sum: "8492", material: "металл."},
        {id: 2, name: "ttttttttttttt ",sum: "8492", material: "металл и пластик и дерево."},
        {id: 3, name: "ttttttttttttt ",sum: "8492", material: "металл и пластик и дерево."},
        {id: 4, name: "ttttttttttttt ",sum: "8492", material: "металл и пластик и дерево."},
    ];
    _block = [
        {id: 1, name: "Проверка наименования",sum: "8492", type:"windows-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 2, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-1", price: "5235" ,descriptionFull:"Проверка полного описания для меню"},
        {id: 3, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 4, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 5, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 6, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 7, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 8, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 9, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 10, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 11, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 12, name: "rywewqerrywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 13, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 14, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 15, name: "r333ywewqrqwerywrey ",sum: "8492", description: "металл.", type:"input-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 17, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 18, name: "r333yeqwrqwewerywrey ",sum: "8492", description: "металл.", type:"input-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 19, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 20, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 21, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 22, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 23, name: "r333yeqwrqwerwerywrey ",sum: "8492", description: "металл.", type:"input-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 24, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 25, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 26, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 27, name: "r333ywrgwererywrey ",sum: "8492", description: "металл.", type:"interior-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 28, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 29, name: "r333teqrtywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 30, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 31, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 32, name: "r333yeqwrqwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 33, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 34, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 35, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 36, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 37, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 38, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 39, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 40, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 41, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 42, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 43, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 44, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 45, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 46, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 47, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 48, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 49, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 50, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 51, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 52, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 53, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 54, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 55, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 56, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 1, name: "Проверка наименования",sum: "8492", description: "Описание товара написанное для теста блока на имнимум 3 строки", type:"windows-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 2, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-1", price: "5235" ,descriptionFull:"Проверка полного описания для меню"},
        {id: 3, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 4, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 5, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 6, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 7, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 8, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 9, name: "2222rywerywrey ",sum: "8492", description: "металл.", type:"windows-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 10, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 11, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 12, name: "rywewqerrywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 13, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 14, name: "rywerywrey ",sum: "8492", description: "металл.", type:"windows-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 15, name: "r333ywewqrqwerywrey ",sum: "8492", description: "металл.", type:"input-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 17, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 18, name: "r333yeqwrqwewerywrey ",sum: "8492", description: "металл.", type:"input-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 19, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 20, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 21, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 22, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 23, name: "r333yeqwrqwerwerywrey ",sum: "8492", description: "металл.", type:"input-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 24, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 25, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"input-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 26, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 27, name: "r333ywrgwererywrey ",sum: "8492", description: "металл.", type:"interior-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 28, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-1", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 29, name: "r333teqrtywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 30, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 31, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-2", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 32, name: "r333yeqwrqwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 33, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 34, name: "r333ywerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 35, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 36, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 37, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 38, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 39, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 40, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 41, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 42, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 43, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 44, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 45, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 46, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 47, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 48, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 49, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 50, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 51, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 52, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 53, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 54, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 55, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
        {id: 56, name: "r333yeqrwwerywrey ",sum: "8492", description: "металл.", type:"interior-doors-3", price: "5235",descriptionFull:"Проверка полного описания для меню"},
]
    getProduct = async () => {
        return this._product;
    };
   
    getBlock = async () => {
        return this._block;
    }

    getInfoById = async (id) => {
        return this._block.filter( (item) => item.id == id);
    };
}
